#cloud-config

coreos:
  units:
  - name: etcd2.service
    command: start
    enable: true
    drop-ins:
    - name: 15-deps.conf
      content: |
        [Unit]
        Description=Etcd2 - unit for etcd
        After=kmsctl-certs.service
        Requires=kmsctl-certs.service
        [Service]
        PermissionsStartOnly=true
        RuntimeDirectory=etcd2
        RuntimeDirectoryMode=0700
        EnvironmentFile=/etc/etcd-environment
        Restart=on-failure
        RestartSec=10
  - name: kmsctl-certs.service
    command: start
    enable: true
    content: |
      [Unit]
      Description=KMSCtl - download certs
      [Service]
      ExecStartPre=/usr/bin/mkdir -p /opt/bin
      ExecStartPre=/usr/bin/mkdir -p /var/lib/etcd2
      ExecStartPre=/usr/bin/mkdir -p /etc/ssl/kubernetes
      ExecStartPre=/usr/bin/chown -R etcd:etcd /etc/ssl/kubernetes /var/lib/etcd2
      ExecStartPre=/usr/bin/chmod 0744 /etc/ssl/kubernetes /var/lib/etcd2
      ExecStartPre=/usr/bin/wget https://github.com/gambol99/kmsctl/releases/download/v1.0.4/kmsctl-linux-amd64 -O /opt/bin/kmsctl
      ExecStartPre=/usr/bin/chmod +x /opt/bin/kmsctl
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${etcdcertobject}
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${etcdkeyobject}
      ExecStartPre=/opt/bin/kmsctl --region ${region} get -b ${bucket} -d /etc/ssl/kubernetes/ ${cacertobject}
      ExecStartPre=/usr/bin/chmod 0644 /etc/ssl/kubernetes/${etcdcertobject} /etc/ssl/kubernetes/${etcdkeyobject} /etc/ssl/kubernetes/${cacertobject}
      ExecStartPre=/usr/bin/bash -c "cp -f /etc/ssl/kubernetes/* /etc/ssl/certs"
      ExecStartPre=/usr/sbin/update-ca-certificates
      ExecStartPre=/usr/bin/chown -R etcd:etcd /etc/ssl/kubernetes /var/lib/etcd2
      ExecStart=/usr/bin/echo "Completed Cert downloads"
      Restart=always
      RestartSec=10
      TimeoutStartSec=300

write_files:
- path: /etc/profile.env
  content: |
    export ETCDCTL_ENDPOINT=https://127.0.0.1:2379
    export ETCDCTL_CA_FILE=/etc/ssl/kubernetes/ca.pem
    export ETCDCTL_CERT_FILE=/etc/ssl/kubernetes/etcd.pem
    export ETCDCTL_KEY_FILE=/etc/ssl/kubernetes/etcdkey.pem
    source /etc/etcd-environment
- path: /etc/etcd-environment
  permissions: 0644
  content: |
    ETCD_TRUSTED_CA_FILE=/etc/ssl/kubernetes/ca.pem
    ETCD_CERT_FILE=/etc/ssl/kubernetes/etcd.pem
    ETCD_KEY_FILE=/etc/ssl/kubernetes/etcdkey.pem
    ETCD_PEER_TRUSTED_CA_FILE=/etc/ssl/kubernetes/ca.pem
    ETCD_PEER_CERT_FILE=/etc/ssl/kubernetes/etcd.pem
    ETCD_PEER_KEY_FILE=/etc/ssl/kubernetes/etcdkey.pem
    ETCD_LISTEN_PEER_URLS=https://0.0.0.0:2380
    ETCD_LISTEN_CLIENT_URLS=https://0.0.0.0:2379
    ETCD_CLIENT_CERT_AUTH=true
    ETCD_PEER_CLIENT_CERT_AUTH=true
    ETCD_INITIAL_CLUSTER=${etcd_memberlist}
    ETCD_PROXY=on
