apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: quay.io/coreos/hyperkube:v1.5.2_coreos.0
    command:
    - /hyperkube
    - apiserver
    - --admission-control=NamespaceLifecycle,NamespaceExists,LimitRanger,ResourceQuota,ServiceAccount,SecurityContextDeny
    - --allow-privileged=true
    - --bind-address=0.0.0.0
    - --etcd-servers=${etcd_memberlist}
    - --secure-port=443
    - --tls-cert-file=/etc/ssl/kubernetes/${mastercertobject}
    - --tls-private-key-file=/etc/ssl/kubernetes/${masterkeyobject}
    - --service-cluster-ip-range=${serviceiprange}
    - --insecure-port=8080
    - --cloud-provider=aws
    - --enable-swagger-ui=true
    - --cloud-config=/etc/kubernetes/cloud.cfg
    - --apiserver-count=${apiservercount}
    - --client-ca-file=/etc/ssl/kubernetes/${cacertobject}
    - --service-account-key-file=/etc/ssl/kubernetes/${masterkeyobject}
    - --runtime-config=extensions/v1beta1/networkpolicies=true
    - --anonymous-auth=false
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        port: 8080
        path: /healthz
      initialDelaySeconds: 15
      timeoutSeconds: 15
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - name: ssl-certs-kubernetes
      mountPath: /etc/ssl/kubernetes
      readOnly: true
    - name: kubernetes
      mountPath: /etc/kubernetes
  volumes:
  - name: ssl-certs-kubernetes
    hostPath:
      path: /etc/ssl/kubernetes
  - name: kubernetes
    hostPath:
      path: /etc/kubernetes
